travis:
  secure:
    BINSTAR_TOKEN: hMm6OkC1kEnNvLss/r9dqOLsN8QU1zVbKFNeti4bV5sID4jSnA5Kx+VlVKXYb7N8S3K01l6lUfQ4D9j7CW5Dte9BmrkYO+6MAJ6fc6HL4cmjIkK/qstEBWNgtwky2eUgReY6/glg674qufWOeSa77UkF54r4Y7fnvbhD7bRUqftTcvBAk+EgLQ9vS4JqtSACHTsPDCprNkXrl1l2pFURX0D6VoEFp86+rMydKMTYWmKYNhnEzhuokfMQmqAyakvKlKwRn8xwxJ6BgKn8RxhX12W/rhv1IOI+w56fXW/mcvlVO/65/1xFhiR7WPZN7HMHsH6q1S5dTLkg8PFTo3bwStxB9DRhWH1q3h6D1jY+VGT2CPKA5nEV6S1q18OXXA9L4IoXJgoV++JE/HEnpNv5mKczKUJlb+601+53uyVHkAB9I2kA65xKMq1hAiDfk8T23309yZzo/ImeiF/Bwm2QIydQAqniFUWOIRmQgjQrFHfdzqGrDnQbschbjApE9lEkqYMCZJcisX8lW3qjMcU57HTRuz4lXRhuxUSvA2LMhr1WE0K5dHtJ4NEtsvrPSHIz3lj3Ec3vxtrmIOtRfBLNwWNC1tUv6N38oypil1n9zSRJhVGfeCvYeD+YYQRK5vcWaxchsGVelHgRJqgC+h4Mj8m37NMf44cdGOPS/SbwYkU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
