travis:
  secure:
    BINSTAR_TOKEN: p9+JViUkPf6H9s4Yc5YImhUmwmo3FEX0R3ecKnozDYIfR9vhyB5p5NUBhX+iLPE6zP5PcgS/hBvQoRTnyaRbShdYE/7HZgqUBEEzlVB4dJgi7k2pBwuipS0uMd8XGLFJtDT/aXutn65uiZ9iLMMYwA/21v/WmaR46H1AMR6n5NuPijaQEx92HxcpHJb5mhCikHShP7bIrxYJ+EgmY44lmEUnFow15GIARr3lR3QOU0xetiMtLiOWrsxr6TLyVGxGCcHiwvjZbuBpsKWtHfbaBGseTR9aJ3OE105drhGJmYjTPMl71M6eRVXgd967Npmc88u7lxa9SLfVFIf5nKlfg8i9nqOsfZ8b3pH78CFC2DLwnVZe8P6TEImfl7zd4aSqo2bEMd4Lnvo0gEPt0ncSTolBKX/DIGIEKKVbI4nbpXNkctIIdaKVNINkiFeAAg6qtZD7VgF3IKsaYYiV7sGyShCMpI5VbPLG4+1PmDu9+dAecTjJOOQi10DWNO/kJRR6Uxr/wFjgW8SNBdlt5uFf1D1c+d26R9AfCMHJzyitWw3qdY5VtKM/n/lrRCaH7t1uTVJdoEahgDfYN3NTaGvdGKdegmieHNsXAxp4X9GDWlwQPbABBkcQs3ayrtFk6ZxXxtCjW3dxo0jsh+PV9MUiHhi0ZXJJDv/Cbp0tC4wFDfY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
