appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: aBHtaias8ea6KwJCbCAgIdJKbQg/A0fS3oGHTJk1b3ukek3Ct1v7BoClN1wm0pq0csvkuKFOW/KB2lQN8t98MF7oBh1R/is+O1B87C/E7jRP39babefTR7o+a82WVsHy7ZQVWOFeKG5Qok9YB6glzXycJ/YsI8sKuzvpiOFveAFhODTlXWMv0F+rcjkWumyrCj+JnPwa5Z3/vZh5jATVwaRKu4gruKjulyOENxaUJ01F02Fh5YnnzwF4N/HL9biJmjEDUllp/XPGuK2MydbBt6VIHbBXaLCYV+TGZYEWtLx3JFOzauUIZJyzVep5AmapiPEy2MoTafJI812FZmxxbgOZ4A83/itSxdbBcYrk/clsZ/QTwKks7Xr0Ee8obc6YdPGiLqoXrMX8mVrVV4h6Cy6dI73pVhDPp0rmYFgoT2y4aAPRvVgvG4eeRZGI+rUxW+F4HYWf32kHBbwMvOaqToFzFqr969TJ5uXuJ2g5NL7VshxLHs0KG2Zh0VQ7qT0DZkVYRas+xzMGUM12IZLJSU+OZsaLPB5kHS9I+jKOZ7YQ8VdAsZpVLfAcJAbjn6TJUGtS54m9iN3AuwUzhFfMSi81R6bUpoT7IC/Rca1ZgFkWsHLV3br0rVEXXiLudgn5r5oUh1QFFtYLm2yNBkAKNB/fXDbn2TuztDeuJD0Fjss=
